export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  FAILED_LOGIN = 'FAILED_LOGIN',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE = 'PASSWORD_RESET_COMPLETE',
  MEMBER_CREATE = 'MEMBER_CREATE',
  MEMBER_UPDATE = 'MEMBER_UPDATE',
  MEMBER_DELETE = 'MEMBER_DELETE',
  VOLUNTEER_CREATE = 'VOLUNTEER_CREATE',
  VOLUNTEER_UPDATE = 'VOLUNTEER_UPDATE',
  VOLUNTEER_DELETE = 'VOLUNTEER_DELETE',
  CREDIT_SCORE_CHANGE = 'CREDIT_SCORE_CHANGE',
  SQUAD_CREATE = 'SQUAD_CREATE',
  SQUAD_UPDATE = 'SQUAD_UPDATE',
  SQUAD_DELETE = 'SQUAD_DELETE',
  TEAM_CREATED = 'TEAM_CREATED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED = 'TEAM_MEMBER_REMOVED',
  TEAM_LEADER_CHANGED = 'TEAM_LEADER_CHANGED',
  TEAM_SCORE_UPDATED = 'TEAM_SCORE_UPDATED',
  TEAM_ARCHIVED = 'TEAM_ARCHIVED',
  TEAM_DELETED = 'TEAM_DELETED',
  EVENT_CREATE = 'EVENT_CREATE',
  EVENT_UPDATE = 'EVENT_UPDATE',
  EVENT_DELETE = 'EVENT_DELETE',
  BLOG_CREATE = 'BLOG_CREATE',
  BLOG_UPDATE = 'BLOG_UPDATE',
  BLOG_DELETE = 'BLOG_DELETE',
  BLOG_PUBLISH = 'BLOG_PUBLISH',
  REPORT_GENERATE = 'REPORT_GENERATE',
  SECURITY_SETTINGS_CHANGE = 'SECURITY_SETTINGS_CHANGE',
}

export interface AuditLogEntry {
  id: string;
  actorId: string;
  actorRole: string;
  actorName?: string;
  action: AuditAction;
  resourceType: string;
  resourceId?: string;
  details?: Record<string, any>;
  ipAddress?: string;
  userAgent?: string;
  result: 'SUCCESS' | 'FAILURE';
  timestamp: Date;
}
