"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditAction = void 0;
var AuditAction;
(function (AuditAction) {
    AuditAction["LOGIN"] = "LOGIN";
    AuditAction["LOGOUT"] = "LOGOUT";
    AuditAction["FAILED_LOGIN"] = "FAILED_LOGIN";
    AuditAction["PASSWORD_CHANGE"] = "PASSWORD_CHANGE";
    AuditAction["PASSWORD_RESET_REQUEST"] = "PASSWORD_RESET_REQUEST";
    AuditAction["PASSWORD_RESET_COMPLETE"] = "PASSWORD_RESET_COMPLETE";
    AuditAction["MEMBER_CREATE"] = "MEMBER_CREATE";
    AuditAction["MEMBER_UPDATE"] = "MEMBER_UPDATE";
    AuditAction["MEMBER_DELETE"] = "MEMBER_DELETE";
    AuditAction["VOLUNTEER_CREATE"] = "VOLUNTEER_CREATE";
    AuditAction["VOLUNTEER_UPDATE"] = "VOLUNTEER_UPDATE";
    AuditAction["VOLUNTEER_DELETE"] = "VOLUNTEER_DELETE";
    AuditAction["CREDIT_SCORE_CHANGE"] = "CREDIT_SCORE_CHANGE";
    AuditAction["SQUAD_CREATE"] = "SQUAD_CREATE";
    AuditAction["SQUAD_UPDATE"] = "SQUAD_UPDATE";
    AuditAction["SQUAD_DELETE"] = "SQUAD_DELETE";
    AuditAction["TEAM_CREATED"] = "TEAM_CREATED";
    AuditAction["TEAM_UPDATED"] = "TEAM_UPDATED";
    AuditAction["TEAM_MEMBER_ADDED"] = "TEAM_MEMBER_ADDED";
    AuditAction["TEAM_MEMBER_REMOVED"] = "TEAM_MEMBER_REMOVED";
    AuditAction["TEAM_LEADER_CHANGED"] = "TEAM_LEADER_CHANGED";
    AuditAction["TEAM_SCORE_UPDATED"] = "TEAM_SCORE_UPDATED";
    AuditAction["TEAM_ARCHIVED"] = "TEAM_ARCHIVED";
    AuditAction["TEAM_DELETED"] = "TEAM_DELETED";
    AuditAction["EVENT_CREATE"] = "EVENT_CREATE";
    AuditAction["EVENT_UPDATE"] = "EVENT_UPDATE";
    AuditAction["EVENT_DELETE"] = "EVENT_DELETE";
    AuditAction["BLOG_CREATE"] = "BLOG_CREATE";
    AuditAction["BLOG_UPDATE"] = "BLOG_UPDATE";
    AuditAction["BLOG_DELETE"] = "BLOG_DELETE";
    AuditAction["BLOG_PUBLISH"] = "BLOG_PUBLISH";
    AuditAction["REPORT_GENERATE"] = "REPORT_GENERATE";
    AuditAction["SECURITY_SETTINGS_CHANGE"] = "SECURITY_SETTINGS_CHANGE";
})(AuditAction || (exports.AuditAction = AuditAction = {}));
//# sourceMappingURL=audit.types.js.map